print("Lua API demo starting")
local frame = website:AddUI("frame", {Size="300x150", Position="50x50"})
website:SetColor(frame, "lightblue")
local label = website:AddUI("label", {Text="Hello World!", Position="10x10"})
website:SetColor(label, "transparent")
local btn = website:AddUI("button", {Text="Click Me!", Position="10x50", Callback=function()
    print("Button clicked!")
    website:SetText(label, "Button was clicked!")
end})
local slider = website:AddUI("slider", {Min=0, Max=100, Value=50, Position="10x90", Callback=function(val)
    website:SetText(label, "Slider: "..val)
end})
local dropdown = website:AddUI("dropdown", {Options={"Red","Green","Blue"}, Position="150x50", Callback=function(val)
    website:SetColor(frame, val:lower())
end})
website:Tween(frame, {width="400px", height="200px"}, 1000)
website:Move(frame, 100, 100, 1000)
website:Fade(frame, 2, 0.5)
local r = website:Random(1, 100)
print("Random number: "..r)
for i=1,3 do
    print("Loop iteration "..i)
end
website:Wait(2)
print("2 seconds passed")
website:OnKey("a", function()
    print("Key A pressed")
end)
website:OnMouseClick(function()
    print("Mouse clicked at x="..website:GetMousePosition().x.." y="..website:GetMousePosition().y)
end)
website:Save("playerScore", 123)
local score = website:Load("playerScore")
print("Loaded score: "..score)
website:Delete("playerScore")
